# Example 0: PyTorch
- https://pytorch.org

In [1]:
import numpy as np
import torch

In [2]:
np.random.seed(1337)
torch.manual_seed(1337)

# Creating tensors

In [3]:
torch.tensor(1)

tensor(1)

In [4]:
torch.from_numpy(np.random.randn(10))

tensor([-0.7032, -0.4903, -0.3218, -1.7551,  0.2067, -2.0113, -0.5573,  0.3372,
         1.5488, -1.3707], dtype=torch.float64)

# Attributes of a torch.Tensor

In [5]:
tensor = torch.rand(3, 5)

print(f'{tensor.shape=}')
print(f'{tensor.dtype=}')
print(f'{tensor.device=}')

tensor.shape=torch.Size([3, 5])
tensor.dtype=torch.float32
tensor.device=device(type='cpu')


# Creating tensors with constant values

In [6]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
torch.full(size=(10, ), fill_value=5.2)

tensor([5.2000, 5.2000, 5.2000, 5.2000, 5.2000, 5.2000, 5.2000, 5.2000, 5.2000,
        5.2000])

## Creating random tensors

In [9]:
torch.rand(10)

tensor([0.2434, 0.6005, 0.7079, 0.5102, 0.4065, 0.8864, 0.3578, 0.8963, 0.9639,
        0.0148])

In [10]:
torch.randn(10)

tensor([ 0.9893, -0.8554, -0.4627, -1.4934,  0.9460, -0.3638, -2.6027,  1.2525,
        -0.2455, -0.3973])

# Operations

In [11]:
x = torch.randn(2)
x_clone = x.clone()
y = torch.randn(2)
print(f'{x=}, {x_clone=}, {y=}')

z = x + y
print(f'{x=}, {x_clone=}, {y=}, {z=}')

z = torch.add(x, y)
print(f'{x=}, {x_clone=}, {y=}, {z=}')

z = x.add(y)
print(f'{x=}, {x_clone=}, {y=}, {z=}')

# in-place operations
z = x.add_(y)
print(f'{x=}, {x_clone=}, {y=}, {z=}')

x=tensor([-0.9511, -0.6433]), x_clone=tensor([-0.9511, -0.6433]), y=tensor([0.6761, 0.8998])
x=tensor([-0.9511, -0.6433]), x_clone=tensor([-0.9511, -0.6433]), y=tensor([0.6761, 0.8998]), z=tensor([-0.2751,  0.2565])
x=tensor([-0.9511, -0.6433]), x_clone=tensor([-0.9511, -0.6433]), y=tensor([0.6761, 0.8998]), z=tensor([-0.2751,  0.2565])
x=tensor([-0.9511, -0.6433]), x_clone=tensor([-0.9511, -0.6433]), y=tensor([0.6761, 0.8998]), z=tensor([-0.2751,  0.2565])
x=tensor([-0.2751,  0.2565]), x_clone=tensor([-0.9511, -0.6433]), y=tensor([0.6761, 0.8998]), z=tensor([-0.2751,  0.2565])


# Data Types
- https://docs.pytorch.org/docs/stable/tensors.html

In [12]:
x = torch.arange(10)
print(f'{x.dtype=}')

y = torch.randn(10)
print(f'{y.dtype=}')

print(f'{y.to(torch.float16).dtype=}')
print(f'{y.half().dtype=}')
print(f'{y.float().dtype=}')
print(f'{y.double().dtype=}')
print(f'{y.int().dtype=}')
print(f'{y.long().dtype=}')

x.dtype=torch.int64
y.dtype=torch.float32
y.to(torch.float16).dtype=torch.float16
y.half().dtype=torch.float16
y.float().dtype=torch.float32
y.double().dtype=torch.float64
y.int().dtype=torch.int32
y.long().dtype=torch.int64


# Accelerators

In [ ]:
if torch.accelerator.is_available():
    print(f'{torch.accelerator.current_accelerator()=}')
    print(f'{torch.accelerator.device_count()=}')

    x = torch.randn(10)
    print(f'{x=}, {x.device=}')

    x = x.to(torch.accelerator.current_accelerator())
    print(f'{x=}, {x.device=}')
    
    x = x.cpu()
    print(f'{x=}, {x.device=}')

    device = torch.device('cuda:0')
    x = x.to(device)
    print(f'{x=}, {x.device=}')
else:
    print('accelerator not found')
    print(f'{x=}, {x.device=}')